"""Initial migration

Revision ID: b9d730b85de2
Revises: 
Create Date: 2024-11-30 12:34:05.068918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d730b85de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('upload_file', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contact',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=8), nullable=False),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('contact_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('list',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('slug', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('list_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=1000000), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('campaign',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('pre_loader', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=1000000), nullable=True),
    sa.Column('campaign_status', sa.String(length=20), nullable=True),
    sa.Column('total_clicks', sa.Integer(), nullable=True),
    sa.Column('unique_clicks', sa.Integer(), nullable=True),
    sa.Column('total_opens', sa.Integer(), nullable=True),
    sa.Column('unique_opens', sa.Integer(), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=True),
    sa.Column('total_ubsubscribes', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['senders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('campaign_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('contact_and_lists',
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.contact_id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.list_id'], )
    )
    op.create_table('campaign_recipient',
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('url_slug', sa.String(length=64), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.contact_id'], ),
    sa.PrimaryKeyConstraint('recipient_id')
    )
    op.create_table('campaign_to_contacts',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.contact_id'], )
    )
    op.create_table('campaign_to_list',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.list_id'], )
    )
    op.create_table('campaign_tracking',
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=120), nullable=True),
    sa.Column('click_url', sa.String(length=300), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['campaign_recipient.recipient_id'], ),
    sa.PrimaryKeyConstraint('tracking_id')
    )
    op.create_table('event_tracking',
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=True),
    sa.Column('click_url', sa.String(length=300), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['campaign_recipient.recipient_id'], ),
    sa.PrimaryKeyConstraint('tracking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_tracking')
    op.drop_table('campaign_tracking')
    op.drop_table('campaign_to_list')
    op.drop_table('campaign_to_contacts')
    op.drop_table('campaign_recipient')
    op.drop_table('contact_and_lists')
    op.drop_table('campaign')
    op.drop_table('templates')
    op.drop_table('senders')
    op.drop_table('list')
    op.drop_table('contact')
    op.drop_table('user')
    # ### end Alembic commands ###
